allow_anonymous false

auth_plugin /mosquitto/go-auth.so
auth_opt_backends http
auth_opt_http_host d81h6zk7-8000.asse.devtunnels.ms
auth_opt_http_port 443
auth_opt_http_with_tls true
auth_opt_http_params_mode form
auth_opt_http_response_mode status
auth_opt_http_getuser_uri /api/webhooks/mqtt/auth/
auth_opt_http_aclcheck_uri /api/webhooks/mqtt/acl/