# Generated by Django 5.2.17 on 2026-10-09 06:59

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import smartlock.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_sensitive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('avatar_url', models.URLField(blank=True, max_length=512, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('two_fa_enabled', models.BooleanField(default=False, help_text='True nếu user có ít nhất 1 phương thức 2FA đang hoạt động. Được đồng bộ tự động bởi sync_two_fa_flag(), KHÔNG set tay.')),
                ('login_failed_attempts', models.IntegerField(default=0)),
                ('login_lock_stage', models.IntegerField(default=0)),
                ('login_locked_until', models.DateTimeField(blank=True, null=True)),
                ('login_last_failed_at', models.DateTimeField(blank=True, null=True)),
                ('login_last_failed_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
        ),
        migrations.CreateModel(
            name='AccessCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('CARD', 'Thẻ RFID'), ('PIN', 'Mã PIN'), ('FACE', 'Khuôn mặt')], max_length=10)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('label', models.CharField(blank=True, help_text='VD: "Khách Booking #123"', max_length=100, null=True)),
                ('card_uid_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('pin_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('embedding_encrypted', models.BinaryField(blank=True, help_text='Vector đặc trưng khuôn mặt (vd. 128 chiều), đã mã hoá Fernet.', null=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.IntegerField(default=1)),
                ('use_count', models.IntegerField(default=0)),
                ('is_revoked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('threshold', models.FloatField(default=0.6)),
                ('consent_confirmed', models.BooleanField(default=False, help_text='Xác nhận người này đã đồng ý được thu thập dữ liệu khuôn mặt (bắt buộc theo NĐ 13/2023).')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccessCard',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('smartlock.accesscredential',),
        ),
        migrations.CreateModel(
            name='DoorPinCode',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('smartlock.accesscredential',),
        ),
        migrations.CreateModel(
            name='FaceProfile',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('smartlock.accesscredential',),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('AUDIT', 'Audit log'), ('NFC', 'NFC log'), ('ACCESS', 'Access event'), ('STATUS', 'Device status log')], max_length=10)),
                ('success', models.BooleanField(default=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('action', models.CharField(blank=True, default='', max_length=50)),
                ('username_attempt', models.CharField(blank=True, max_length=150, null=True)),
                ('event_type', models.CharField(blank=True, choices=[('TAP_SUCCESS', 'Tap Success'), ('TAP_FAILED', 'Tap Failed'), ('CARD_REGISTER', 'Card Register'), ('READER_CONNECTED', 'Reader Connected'), ('READER_DISCONNECTED', 'Reader Disconnected'), ('CONFIG_UPDATED', 'Config Updated'), ('SESSION_TIMEOUT', 'Session Timeout')], default='', max_length=50)),
                ('method', models.CharField(blank=True, choices=[('RFID', 'Thẻ RFID'), ('PIN', 'Mã PIN'), ('FACE', 'Khuôn mặt'), ('BLE', 'Bluetooth'), ('NFC_PHONE', 'NFC trên điện thoại')], default='', max_length=10)),
                ('reason', models.CharField(blank=True, help_text='Lý do thất bại, nếu có.', max_length=100, null=True)),
                ('confidence', models.FloatField(blank=True, help_text='Độ tin cậy nhận diện khuôn mặt (nếu có).', null=True)),
                ('snapshot_url', models.URLField(blank=True, help_text='Ảnh chụp lúc mở cửa, lưu ở object storage (MinIO/S3), khuyến nghị giữ tối đa 30 ngày.', max_length=512, null=True)),
                ('battery_level', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('signal_strength', models.IntegerField(blank=True, null=True)),
                ('lock_state', models.CharField(blank=True, choices=[('locked', 'Locked'), ('unlocked', 'Unlocked'), ('jammed', 'Jam'), ('unknown', 'Unknown')], default='', max_length=20)),
                ('tamper_detected', models.BooleanField(default=False)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_events_as_card', to='smartlock.accesscredential')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_actor', to=settings.AUTH_USER_MODEL)),
                ('door_pin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_events_as_pin', to='smartlock.accesscredential')),
                ('face_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_events_as_face', to='smartlock.accesscredential')),
                ('nfc_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfc_logs', to='smartlock.accesscredential')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_target', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccessEvent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('smartlock.activitylog',),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('smartlock.activitylog',),
        ),
        migrations.CreateModel(
            name='DeviceStatusLog',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('smartlock.activitylog',),
        ),
        migrations.CreateModel(
            name='NfcLog',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('smartlock.activitylog',),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger')], default='info', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_code', models.CharField(max_length=50, unique=True)),
                ('provisioning_secret_hash', models.CharField(max_length=255)),
                ('device_mode', models.CharField(choices=[('physical', 'Physical'), ('simulated', 'Simulated')], default='physical', max_length=20)),
                ('is_purchased', models.BooleanField(default=False, help_text='True khi thiết bị đã được khách mua/kích hoạt chính thức, khác với thiết bị demo/dùng thử nội bộ. Chỉ thiết bị đã mua mới được tính vào doanh số.')),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator('^([0-9A-F]{2}:){5}[0-9A-F]{2}$', 'MAC phải dạng AA:BB:CC:DD:EE:FF (chữ hoa).')])),
                ('firmware_version', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('maintenance', 'Maintenance'), ('provisioning', 'Provisioning'), ('revoked', 'Revoked (đã factory reset, chờ gán chủ mới)')], default='provisioning', max_length=20)),
                ('battery_level', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('bluetooth_enabled', models.BooleanField(default=True)),
                ('wifi_enabled', models.BooleanField(default=True)),
                ('nfc_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CardDeviceAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('access_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartlock.accesscredential')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartlock.device')),
            ],
        ),
        migrations.AddField(
            model_name='activitylog',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='smartlock.device'),
        ),
        migrations.AddField(
            model_name='accesscredential',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='smartlock.device'),
        ),
        migrations.CreateModel(
            name='DeviceCommand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command_type', models.CharField(choices=[('UNLOCK', 'Unlock'), ('LOCK', 'Lock'), ('ADD_CARD', 'Add Card'), ('REMOVE_CARD', 'Remove Card'), ('RESET', 'Reset'), ('OTA_UPDATE', 'OTA Update'), ('REBOOT', 'Reboot'), ('PING', 'Ping (kiểm tra kết nối)')], max_length=50)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('acknowledged', 'Acknowledged'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('command_token_hash', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartlock.device')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NfcReader',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reader_mode', models.CharField(choices=[('physical', 'Physical'), ('simulated', 'Simulated')], max_length=20)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('auto_register', models.BooleanField(default=False)),
                ('auto_register_until', models.DateTimeField(blank=True, null=True)),
                ('grant_permission', models.JSONField(default=list)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartlock.device')),
            ],
        ),
        migrations.AddField(
            model_name='activitylog',
            name='reader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='smartlock.nfcreader'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartlock.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('DIRECT', 'Chủ thiết bị chia sẻ trực tiếp'), ('SHARE_CODE', 'Mã chia sẻ (cũ)')], default='DIRECT', max_length=20)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('accepted', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_deviceaccesses', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartlock.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_deviceaccesses', to=settings.AUTH_USER_MODEL)),
                ('permissions', models.ManyToManyField(blank=True, related_name='device_accesses', to='smartlock.permission')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('OTP', 'One-time code'), ('SESSION', 'Mobile session'), ('PASSKEY', 'Passkey / FIDO2'), ('TFCONFIG', '2FA config')], max_length=10)),
                ('purpose', models.CharField(blank=True, choices=[('EMAIL_VERIFY', 'Verify email'), ('PASSWORD_RESET', 'Password reset'), ('SUPPORT_AUTH', 'Support auth'), ('RECOVERY_CONFIRM', 'Recovery confirm'), ('UPDATE_INFO', 'Update info'), ('TF_SETUP', '2FA email - thiết lập'), ('TF_VERIFY', '2FA email - xác thực')], default='', max_length=50)),
                ('token_hash', models.CharField(blank=True, default='', max_length=255)),
                ('attempts', models.IntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('refresh_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('prev_refresh_hash', models.CharField(blank=True, default='', max_length=64)),
                ('device_name', models.CharField(blank=True, default='', max_length=100)),
                ('platform', models.CharField(blank=True, default='', max_length=20)),
                ('app_version', models.CharField(blank=True, default='', max_length=30)),
                ('fcm_token', models.CharField(blank=True, default='', max_length=512)),
                ('push_enabled', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, max_length=512, null=True)),
                ('public_key', models.BinaryField(blank=True, null=True)),
                ('sign_count', models.BigIntegerField(default=0)),
                ('transports', models.JSONField(blank=True, default=list)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('rp_id', models.CharField(blank=True, max_length=255, null=True)),
                ('totp_secret_encrypted', models.CharField(blank=True, default='', max_length=255)),
                ('totp_confirmed', models.BooleanField(default=False)),
                ('totp_last_step', models.BigIntegerField(default=0)),
                ('email_otp_enabled', models.BooleanField(default=False)),
                ('preferred_method', models.CharField(blank=True, choices=[('totp', 'Google Authenticator (TOTP)'), ('fido2', 'Passkey / FIDO2'), ('email', 'Email OTP')], default='', max_length=10)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fido2Credential',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('smartlock.securityrecord',),
        ),
        migrations.CreateModel(
            name='MobileSession',
            fields=[
            ],
            options={
                'ordering': ['-created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('smartlock.securityrecord',),
        ),
        migrations.CreateModel(
            name='OneTimeCode',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('smartlock.securityrecord',),
        ),
        migrations.CreateModel(
            name='TwoFactorConfig',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('smartlock.securityrecord',),
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.SmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('registration_enabled', models.BooleanField(default=True)),
                ('verification_token_expiry_minutes', models.IntegerField(default=30)),
                ('share_code_expiry_minutes', models.IntegerField(default=15)),
                ('login_lockout_stage_minutes', models.JSONField(default=smartlock.models.default_lockout_stage_minutes)),
                ('session_timeout_hours', models.IntegerField(default=24)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='uniq_user_email_ci'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='uniq_user_username_ci'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('login_failed_attempts__gte', 0), ('login_lock_stage__gte', 0)), name='chk_user_lock_counters_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner__isnull', True), ('status__in', ('provisioning', 'revoked'))), models.Q(models.Q(('status__in', ('provisioning', 'revoked')), _negated=True), ('owner__isnull', False)), _connector='OR'), name='chk_devices_owner_vs_status'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.CheckConstraint(condition=models.Q(('battery_level__gte', 0), ('battery_level__lte', 100)), name='chk_device_battery_range'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.CheckConstraint(condition=models.Q(('is_purchased', False), ('purchased_at__isnull', False), _connector='OR'), name='chk_device_purchased_has_date'),
        ),
        migrations.AddConstraint(
            model_name='carddeviceaccess',
            constraint=models.UniqueConstraint(fields=('access_card', 'device'), name='uniq_card_device'),
        ),
        migrations.AddIndex(
            model_name='accesscredential',
            index=models.Index(fields=['kind', 'user'], name='idx_cred_kind_user'),
        ),
        migrations.AddIndex(
            model_name='accesscredential',
            index=models.Index(fields=['kind', 'device'], name='idx_cred_kind_device'),
        ),
        migrations.AddIndex(
            model_name='accesscredential',
            index=models.Index(fields=['device', 'expires_at'], name='idx_cred_dev_exp'),
        ),
        migrations.AddConstraint(
            model_name='accesscredential',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['CARD', 'PIN', 'FACE'])), name='chk_cred_kind'),
        ),
        migrations.AddConstraint(
            model_name='accesscredential',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'CARD')), fields=('card_uid_hash',), name='uniq_cred_card_uid'),
        ),
        migrations.AddConstraint(
            model_name='accesscredential',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'CARD'), _negated=True), models.Q(('card_uid_hash__isnull', False), ('user__isnull', False)), _connector='OR'), name='chk_cred_card_required'),
        ),
        migrations.AddConstraint(
            model_name='accesscredential',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'PIN'), _negated=True), models.Q(('max_uses__gte', 0), ('use_count__gte', 0)), _connector='OR'), name='chk_cred_pin_uses_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='accesscredential',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'PIN'), _negated=True), models.Q(('expires_at__isnull', False), ('expires_at__gt', models.F('valid_from'))), _connector='OR'), name='chk_cred_pin_expiry'),
        ),
        migrations.AddConstraint(
            model_name='accesscredential',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'PIN'), _negated=True), ('is_revoked', False), ('revoked_at__isnull', False), _connector='OR'), name='chk_cred_pin_revoked_date'),
        ),
        migrations.AddConstraint(
            model_name='accesscredential',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'PIN'), _negated=True), models.Q(('pin_hash__isnull', False), ('device__isnull', False), ('created_by__isnull', False)), _connector='OR'), name='chk_cred_pin_required'),
        ),
        migrations.AddConstraint(
            model_name='accesscredential',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'FACE')), fields=('user', 'device'), name='uniq_cred_face_user_device'),
        ),
        migrations.AddConstraint(
            model_name='accesscredential',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'FACE'), _negated=True), models.Q(('threshold__gt', 0), ('threshold__lte', 2)), _connector='OR'), name='chk_cred_face_threshold'),
        ),
        migrations.AddConstraint(
            model_name='accesscredential',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'FACE'), _negated=True), ('is_active', False), ('consent_confirmed', True), _connector='OR'), name='chk_cred_face_active_consent'),
        ),
        migrations.AddConstraint(
            model_name='accesscredential',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'FACE'), _negated=True), models.Q(('user__isnull', False), ('device__isnull', False)), _connector='OR'), name='chk_cred_face_required'),
        ),
        migrations.AddIndex(
            model_name='devicecommand',
            index=models.Index(fields=['device', 'created_at'], name='idx_devcommand_dev_time'),
        ),
        migrations.AddIndex(
            model_name='nfcreader',
            index=models.Index(fields=['device', 'created_at'], name='idx_nfcreader_dev_time'),
        ),
        migrations.AddConstraint(
            model_name='nfcreader',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__isnull', True), ('expires_at__gt', models.F('valid_from')), _connector='OR'), name='chk_nfcreader_expiry'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['kind', 'created_at'], name='idx_actlog_kind_time'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['device', 'kind', 'created_at'], name='idx_actlog_dev_kind_time'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['actor_user', 'created_at'], name='idx_actlog_actor_time'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', 'created_at'], name='idx_actlog_user_time'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['device', 'method', 'success', 'created_at'], name='idx_actlog_method_ok'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['device', 'recorded_at'], name='idx_actlog_dev_rec'),
        ),
        migrations.AddConstraint(
            model_name='activitylog',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['AUDIT', 'NFC', 'ACCESS', 'STATUS'])), name='chk_actlog_kind'),
        ),
        migrations.AddConstraint(
            model_name='activitylog',
            constraint=models.CheckConstraint(condition=models.Q(('battery_level__isnull', True), models.Q(('battery_level__gte', 0), ('battery_level__lte', 100)), _connector='OR'), name='chk_actlog_battery_range'),
        ),
        migrations.AddConstraint(
            model_name='activitylog',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'STATUS'), _negated=True), models.Q(('battery_level__isnull', False), models.Q(('lock_state', ''), _negated=True)), _connector='OR'), name='chk_actlog_status_required'),
        ),
        migrations.AddConstraint(
            model_name='activitylog',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'ACCESS'), _negated=True), models.Q(('method', ''), _negated=True), _connector='OR'), name='chk_actlog_access_method'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'created_at'], name='idx_notification_user_time'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(('read_at__isnull', True), ('is_read', True), _connector='OR'), name='chk_notification_readat_requires_read'),
        ),
        migrations.AddConstraint(
            model_name='deviceaccess',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__isnull', True), ('expires_at__gt', models.F('valid_from')), _connector='OR'), name='chk_device_access_expiry'),
        ),
        migrations.AddConstraint(
            model_name='deviceaccess',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('device', 'user'), name='uniq_active_device_access'),
        ),
        migrations.AddIndex(
            model_name='securityrecord',
            index=models.Index(fields=['user', 'kind', 'purpose', 'created_at'], name='idx_secrec_user_purpose'),
        ),
        migrations.AddIndex(
            model_name='securityrecord',
            index=models.Index(fields=['user', 'kind', 'revoked_at'], name='idx_secrec_user_rev'),
        ),
        migrations.AddIndex(
            model_name='securityrecord',
            index=models.Index(condition=models.Q(('kind', 'SESSION')), fields=['prev_refresh_hash'], name='idx_secrec_prev_refresh'),
        ),
        migrations.AddIndex(
            model_name='securityrecord',
            index=models.Index(condition=models.Q(('kind', 'SESSION')), fields=['fcm_token'], name='idx_secrec_fcm'),
        ),
        migrations.AddConstraint(
            model_name='securityrecord',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['OTP', 'SESSION', 'PASSKEY', 'TFCONFIG'])), name='chk_secrec_kind'),
        ),
        migrations.AddConstraint(
            model_name='securityrecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'OTP'), _negated=True), ('attempts__gte', 0), _connector='OR'), name='chk_secrec_otp_attempts'),
        ),
        migrations.AddConstraint(
            model_name='securityrecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'OTP'), _negated=True), ('used_at__isnull', True), ('is_used', True), _connector='OR'), name='chk_secrec_otp_usedat'),
        ),
        migrations.AddConstraint(
            model_name='securityrecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'OTP'), _negated=True), models.Q(models.Q(('purpose', ''), _negated=True), ('expires_at__isnull', False)), _connector='OR'), name='chk_secrec_otp_required'),
        ),
        migrations.AddConstraint(
            model_name='securityrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'SESSION')), fields=('refresh_hash',), name='uniq_secrec_refresh_hash'),
        ),
        migrations.AddConstraint(
            model_name='securityrecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'SESSION'), _negated=True), models.Q(('refresh_hash__isnull', False), ('expires_at__gt', models.F('created_at'))), _connector='OR'), name='chk_secrec_session'),
        ),
        migrations.AddConstraint(
            model_name='securityrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'PASSKEY')), fields=('credential_id',), name='uniq_secrec_credential_id'),
        ),
        migrations.AddConstraint(
            model_name='securityrecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'PASSKEY'), _negated=True), models.Q(('credential_id__isnull', False), ('public_key__isnull', False)), _connector='OR'), name='chk_secrec_passkey'),
        ),
        migrations.AddConstraint(
            model_name='securityrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'TFCONFIG')), fields=('user',), name='uniq_secrec_tfconfig_user'),
        ),
        migrations.AddConstraint(
            model_name='systemsettings',
            constraint=models.CheckConstraint(condition=models.Q(('id', 1)), name='chk_settings_singleton'),
        ),
        migrations.AddConstraint(
            model_name='systemsettings',
            constraint=models.CheckConstraint(condition=models.Q(('session_timeout_hours__gte', 1), ('session_timeout_hours__lte', 720), ('share_code_expiry_minutes__gte', 1), ('share_code_expiry_minutes__lte', 1440), ('verification_token_expiry_minutes__gte', 1), ('verification_token_expiry_minutes__lte', 10080)), name='chk_settings_ranges'),
        ),
    ]
