# Generated by Django 5.2.17 on 2026-09-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlock', '0003_fido2credential_twofactorconfig_twofactorbackupcode_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='device',
            name='chk_devices_owner_vs_status',
        ),
        migrations.RemoveField(
            model_name='shareaccesscode',
            name='code_encrypted',
        ),
        migrations.RemoveField(
            model_name='twofactorconfig',
            name='is_enabled',
        ),
        migrations.AddField(
            model_name='shareaccesscode',
            name='code_hash',
            field=models.CharField(db_index=True, default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='two_fa_enabled',
            field=models.BooleanField(default=False, help_text='True nếu user có ít nhất 1 phương thức 2FA đang hoạt động. Được đồng bộ tự động bởi sync_two_fa_flag(), KHÔNG set tay.'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('maintenance', 'Maintenance'), ('provisioning', 'Provisioning'), ('revoked', 'Revoked (đã factory reset, chờ gán chủ mới)')], default='provisioning', max_length=20),
        ),
        migrations.AddIndex(
            model_name='shareaccesscode',
            index=models.Index(fields=['code_hash', 'expires_at'], name='idx_sharecode_hash_exp'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner__isnull', True), ('status__in', ('provisioning', 'revoked'))), models.Q(models.Q(('status__in', ('provisioning', 'revoked')), _negated=True), ('owner__isnull', False)), _connector='OR'), name='chk_devices_owner_vs_status'),
        ),
    ]
