# Generated by Django 5.2.17 on 2026-09-29 01:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlock', '0006_doorpincode_faceprofile_accessevent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginattemptlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='loginidentifier',
            name='user',
        ),
        migrations.RemoveField(
            model_name='loginlockout',
            name='user',
        ),
        migrations.RemoveField(
            model_name='nfcreaderconfig',
            name='reader',
        ),
        migrations.RemoveField(
            model_name='nfcsession',
            name='device',
        ),
        migrations.RemoveField(
            model_name='nfcsession',
            name='nfc_tag',
        ),
        migrations.RemoveField(
            model_name='nfcsession',
            name='reader',
        ),
        migrations.RemoveField(
            model_name='nfcsession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='twofactorbackupcode',
            name='user',
        ),
        migrations.RemoveField(
            model_name='twofactoremailcode',
            name='user',
        ),
        migrations.AddField(
            model_name='nfcreader',
            name='auto_register',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nfcreader',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfcreader',
            name='grant_permission',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='nfcreader',
            name='valid_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='login_failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='login_last_failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='login_last_failed_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='login_lock_stage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='login_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OneTimeCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('EMAIL_VERIFY', 'Verify email'), ('PASSWORD_RESET', 'Password reset'), ('SUPPORT_AUTH', 'Support auth'), ('RECOVERY_CONFIRM', 'Recovery confirm'), ('UPDATE_INFO', 'Update info'), ('TF_SETUP', '2FA email - thiết lập'), ('TF_VERIFY', '2FA email - xác thực')], max_length=50)),
                ('token_hash', models.CharField(max_length=255)),
                ('attempts', models.IntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_time_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='EmailVerificationToken',
        ),
        migrations.DeleteModel(
            name='LoginAttemptLog',
        ),
        migrations.DeleteModel(
            name='LoginIdentifier',
        ),
        migrations.DeleteModel(
            name='LoginLockout',
        ),
        migrations.DeleteModel(
            name='NfcReaderConfig',
        ),
        migrations.DeleteModel(
            name='NfcSession',
        ),
        migrations.DeleteModel(
            name='TwoFactorBackupCode',
        ),
        migrations.DeleteModel(
            name='TwoFactorEmailCode',
        ),
        migrations.AddIndex(
            model_name='onetimecode',
            index=models.Index(fields=['user', 'purpose', 'created_at'], name='idx_otc_user_purpose'),
        ),
    ]
