# Generated by Django 5.2.17 on 2026-09-30 07:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlock', '0007_remove_loginattemptlog_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refresh_hash', models.CharField(max_length=64, unique=True)),
                ('prev_refresh_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('device_name', models.CharField(blank=True, default='', max_length=100)),
                ('platform', models.CharField(default='android', max_length=20)),
                ('app_version', models.CharField(blank=True, default='', max_length=30)),
                ('fcm_token', models.CharField(blank=True, db_index=True, default='', max_length=512)),
                ('push_enabled', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'revoked_at'], name='idx_mobsess_user_rev')],
            },
        ),
    ]
