# Generated by Django 5.2.17 on 2026-10-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlock', '0009_alter_accessevent_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automationrulelog',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='automationrulelog',
            name='device',
        ),
        migrations.RemoveField(
            model_name='automationrulelog',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='shareaccesscode',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='shareaccesscode',
            name='device',
        ),
        migrations.RemoveField(
            model_name='shareaccesscode',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='supportrequest',
            name='device',
        ),
        migrations.RemoveField(
            model_name='supportrequest',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='supportrequest',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='ip_whitelist',
        ),
        migrations.AddField(
            model_name='nfcreader',
            name='auto_register_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accessevent',
            name='method',
            field=models.CharField(choices=[('RFID', 'Thẻ RFID'), ('PIN', 'Mã PIN'), ('FACE', 'Khuôn mặt'), ('BLE', 'Bluetooth'), ('NFC_PHONE', 'NFC trên điện thoại')], max_length=10),
        ),
        migrations.AlterField(
            model_name='device',
            name='is_purchased',
            field=models.BooleanField(default=False, help_text='True khi thiết bị đã được khách mua/kích hoạt chính thức, khác với thiết bị demo/dùng thử nội bộ. Chỉ thiết bị đã mua mới được tính vào doanh số.'),
        ),
        migrations.AlterField(
            model_name='deviceaccess',
            name='accepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='deviceaccess',
            name='source',
            field=models.CharField(choices=[('DIRECT', 'Chủ thiết bị chia sẻ trực tiếp'), ('SHARE_CODE', 'Mã chia sẻ (cũ)')], default='DIRECT', max_length=20),
        ),
        migrations.AlterField(
            model_name='devicecommand',
            name='command_type',
            field=models.CharField(choices=[('UNLOCK', 'Unlock'), ('LOCK', 'Lock'), ('ADD_CARD', 'Add Card'), ('REMOVE_CARD', 'Remove Card'), ('RESET', 'Reset'), ('OTA_UPDATE', 'OTA Update'), ('REBOOT', 'Reboot'), ('PING', 'Ping (kiểm tra kết nối)')], max_length=50),
        ),
        migrations.DeleteModel(
            name='AutomationRule',
        ),
        migrations.DeleteModel(
            name='AutomationRuleLog',
        ),
        migrations.DeleteModel(
            name='ShareAccessCode',
        ),
        migrations.DeleteModel(
            name='SupportRequest',
        ),
    ]
