# Generated by Django 5.2.17 on 2026-10-01 12:39

import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('smartlock', '0010_remove_automationrulelog_rule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator('^([0-9A-F]{2}:){5}[0-9A-F]{2}$', 'MAC phải dạng AA:BB:CC:DD:EE:FF (chữ hoa).')]),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.CheckConstraint(condition=models.Q(('battery_level__gte', 0), ('battery_level__lte', 100)), name='chk_device_battery_range'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.CheckConstraint(condition=models.Q(('is_purchased', False), ('purchased_at__isnull', False), _connector='OR'), name='chk_device_purchased_has_date'),
        ),
        migrations.AddConstraint(
            model_name='deviceaccess',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('device', 'user'), name='uniq_active_device_access'),
        ),
        migrations.AddConstraint(
            model_name='devicestatuslog',
            constraint=models.CheckConstraint(condition=models.Q(('battery_level__gte', 0), ('battery_level__lte', 100)), name='chk_statuslog_battery_range'),
        ),
        migrations.AddConstraint(
            model_name='doorpincode',
            constraint=models.CheckConstraint(condition=models.Q(('max_uses__gte', 0), ('use_count__gte', 0)), name='chk_doorpin_uses_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='doorpincode',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('valid_from'))), name='chk_doorpin_expiry'),
        ),
        migrations.AddConstraint(
            model_name='doorpincode',
            constraint=models.CheckConstraint(condition=models.Q(('is_revoked', False), ('revoked_at__isnull', False), _connector='OR'), name='chk_doorpin_revoked_has_date'),
        ),
        migrations.AddConstraint(
            model_name='faceprofile',
            constraint=models.CheckConstraint(condition=models.Q(('threshold__gt', 0), ('threshold__lte', 2)), name='chk_face_threshold_range'),
        ),
        migrations.AddConstraint(
            model_name='faceprofile',
            constraint=models.CheckConstraint(condition=models.Q(('is_active', False), ('consent_confirmed', True), _connector='OR'), name='chk_face_active_requires_consent'),
        ),
        migrations.AddConstraint(
            model_name='mobilesession',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='chk_mobsession_expiry'),
        ),
        migrations.AddConstraint(
            model_name='nfcreader',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__isnull', True), ('expires_at__gt', models.F('valid_from')), _connector='OR'), name='chk_nfcreader_expiry'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(('read_at__isnull', True), ('is_read', True), _connector='OR'), name='chk_notification_readat_requires_read'),
        ),
        migrations.AddConstraint(
            model_name='onetimecode',
            constraint=models.CheckConstraint(condition=models.Q(('attempts__gte', 0)), name='chk_otc_attempts_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='onetimecode',
            constraint=models.CheckConstraint(condition=models.Q(('used_at__isnull', True), ('is_used', True), _connector='OR'), name='chk_otc_usedat_requires_used'),
        ),
        migrations.AddConstraint(
            model_name='systemsettings',
            constraint=models.CheckConstraint(condition=models.Q(('id', 1)), name='chk_settings_singleton'),
        ),
        migrations.AddConstraint(
            model_name='systemsettings',
            constraint=models.CheckConstraint(condition=models.Q(('session_timeout_hours__gte', 1), ('session_timeout_hours__lte', 720), ('share_code_expiry_minutes__gte', 1), ('share_code_expiry_minutes__lte', 1440), ('verification_token_expiry_minutes__gte', 1), ('verification_token_expiry_minutes__lte', 10080)), name='chk_settings_ranges'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='uniq_user_email_ci'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='uniq_user_username_ci'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('login_failed_attempts__gte', 0), ('login_lock_stage__gte', 0)), name='chk_user_lock_counters_nonneg'),
        ),
    ]
