# Generated by Django 5.2.17 on 2026-10-02 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartlock', '0011_alter_device_mac_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='ip_blacklist',
        ),
    ]
