[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = -DCORE_DEBUG_LEVEL=0
lib_deps =
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.0.0
    madhephaestus/ESP32Servo@^3.0.0
    chris--a/Keypad@^3.1.1
    ; bỏ dấu ; ở dòng dưới nếu dùng USE_MFRC522 1
    ; miguelbalboa/MFRC522@^1.4.11