# Generated by Django 5.2.17 on 2026-09-20 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartlock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='is_purchased',
        ),
    ]
