# Generated by Django 5.2.17 on 2026-09-25 02:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlock', '0004_remove_device_chk_devices_owner_vs_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_purchased',
            field=models.BooleanField(default=False, help_text='True khi thiết bị đã được khách mua/kích hoạt chính thức, khác với thiết bị demo/dùng thử nội bộ. Chỉ thiết bị đã mua mới được tính vào doanh số và được cấp bảo hành/hỗ trợ (SupportRequest).'),
        ),
        migrations.AddField(
            model_name='device',
            name='purchased_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('trigger_type', models.CharField(choices=[('BATTERY_LOW', 'Pin yếu dưới ngưỡng (%)'), ('OFFLINE_TOO_LONG', 'Mất kết nối quá lâu (giây)'), ('FAILED_ACCESS_BURST', 'Quẹt thẻ / nhập sai liên tiếp (số lần trong khoảng thời gian)'), ('DOOR_OPEN_TOO_LONG', 'Cửa mở quá lâu chưa đóng (giây)'), ('TAMPER_DETECTED', 'Phát hiện tác động vật lý (tamper)'), ('TEMPERATURE_OUT_OF_RANGE', 'Nhiệt độ vượt ngưỡng (°C)')], max_length=30)),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=2, help_text='VD: 20 (pin %), 300 (giây), 3 (số lần thất bại), 40 (°C).', max_digits=8, null=True)),
                ('threshold_window_seconds', models.IntegerField(blank=True, help_text='Khoảng thời gian tính ngưỡng cho các luật kiểu "N lần trong X giây".', null=True)),
                ('action_type', models.CharField(choices=[('NOTIFY_ONLY', 'Chỉ gửi thông báo'), ('AUTO_LOCK', 'Tự động khoá cửa (gửi lệnh LOCK)'), ('TEMP_BLOCK_ACCESS', 'Tạm khoá quyền truy cập của thẻ/user liên quan')], default='NOTIFY_ONLY', max_length=30)),
                ('notify_severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('cooldown_seconds', models.IntegerField(default=300, help_text='Không kích hoạt lại luật này trong khoảng thời gian sau lần kích hoạt gần nhất, tránh spam thông báo khi điều kiện vẫn còn đúng.')),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(blank=True, help_text='Để trống = áp dụng cho mọi thiết bị của owner.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='smartlock.device')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AutomationRuleLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('measured_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('action_taken', models.CharField(max_length=30)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartlock.device')),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rule_log_entries', to='smartlock.notification')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='smartlock.automationrule')),
            ],
        ),
        migrations.AddIndex(
            model_name='automationrule',
            index=models.Index(fields=['owner', 'is_active'], name='idx_autorule_owner_active'),
        ),
        migrations.AddIndex(
            model_name='automationrule',
            index=models.Index(fields=['device', 'trigger_type'], name='idx_autorule_dev_trigger'),
        ),
        migrations.AddIndex(
            model_name='automationrulelog',
            index=models.Index(fields=['rule', 'triggered_at'], name='idx_autorulelog_rule_time'),
        ),
    ]
