# Generated by Django 5.2.17 on 2026-09-25 07:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlock', '0005_device_is_purchased_device_purchased_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoorPinCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, help_text='VD: "Khách Booking #123"', max_length=100, null=True)),
                ('pin_hash', models.CharField(max_length=255)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('max_uses', models.IntegerField(default=1)),
                ('use_count', models.IntegerField(default=0)),
                ('is_revoked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_door_pins', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='door_pins', to='smartlock.device')),
            ],
        ),
        migrations.CreateModel(
            name='FaceProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('embedding_encrypted', models.BinaryField(help_text='Vector đặc trưng khuôn mặt (vd. 128 chiều), đã mã hoá Fernet.')),
                ('threshold', models.FloatField(default=0.6)),
                ('consent_confirmed', models.BooleanField(default=False, help_text='Xác nhận người này đã đồng ý được thu thập dữ liệu khuôn mặt (bắt buộc theo NĐ 13/2023).')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_profiles', to='smartlock.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccessEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('RFID', 'Thẻ RFID'), ('PIN', 'Mã PIN'), ('FACE', 'Khuôn mặt')], max_length=10)),
                ('success', models.BooleanField()),
                ('reason', models.CharField(blank=True, help_text='Lý do thất bại, nếu có.', max_length=100, null=True)),
                ('confidence', models.FloatField(blank=True, help_text='Độ tin cậy nhận diện khuôn mặt (nếu có).', null=True)),
                ('snapshot_url', models.URLField(blank=True, help_text='Ảnh chụp lúc mở cửa, lưu ở object storage (MinIO/S3), khuyến nghị giữ tối đa 30 ngày.', max_length=512, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartlock.accesscard')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_events', to='smartlock.device')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('door_pin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartlock.doorpincode')),
                ('face_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartlock.faceprofile')),
            ],
        ),
        migrations.AddIndex(
            model_name='doorpincode',
            index=models.Index(fields=['device', 'expires_at'], name='idx_doorpin_dev_exp'),
        ),
        migrations.AddConstraint(
            model_name='faceprofile',
            constraint=models.UniqueConstraint(fields=('user', 'device'), name='uniq_faceprofile_user_device'),
        ),
        migrations.AddIndex(
            model_name='accessevent',
            index=models.Index(fields=['device', 'created_at'], name='idx_accessevt_dev_time'),
        ),
        migrations.AddIndex(
            model_name='accessevent',
            index=models.Index(fields=['device', 'method', 'success', 'created_at'], name='idx_accessevt_method_ok'),
        ),
    ]
