# Generated by Django 5.2.17 on 2026-10-01 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlock', '0008_mobilesession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessevent',
            name='method',
            field=models.CharField(choices=[('RFID', 'Thẻ RFID'), ('PIN', 'Mã PIN'), ('FACE', 'Khuôn mặt'), ('BLE', 'Bluetooth')], max_length=10),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='threshold_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='VD: 20 (pin %), 300 (giây).', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='threshold_window_seconds',
            field=models.IntegerField(blank=True, help_text='Không còn dùng (trước đây cho luật "N lần sai trong X giây"; nay khoá tạm nằm ở services.py).', null=True),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='trigger_type',
            field=models.CharField(choices=[('BATTERY_LOW', 'Pin yếu dưới ngưỡng (%)'), ('OFFLINE_TOO_LONG', 'Mất kết nối quá lâu (giây)'), ('DOOR_OPEN_TOO_LONG', 'Cửa mở quá lâu chưa đóng (giây)'), ('TAMPER_DETECTED', 'Phát hiện tác động vật lý (tamper)')], max_length=30),
        ),
    ]
