# Generated by Django 5.2.17 on 2026-09-15 07:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_code', models.CharField(max_length=50, unique=True)),
                ('provisioning_secret_hash', models.CharField(max_length=255)),
                ('device_mode', models.CharField(default='physical', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(default='provisioning', max_length=20)),
                ('battery_level', models.IntegerField(default=100)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('bluetooth_enabled', models.BooleanField(default=True)),
                ('wifi_enabled', models.BooleanField(default=True)),
                ('nfc_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'devices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('severity', models.CharField(default='info', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications',
                'managed': False,
            },
        ),
    ]
