# Generated by Django 5.2.17 on 2026-09-16 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotpcredential',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hotp_credential', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nfcreaderconfig',
            name='reader',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='smartlock.nfcreader'),
        ),
        migrations.AlterField(
            model_name='totpcredential',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='totp_credential', to=settings.AUTH_USER_MODEL),
        ),
    ]
