[platformio]
src_dir = .

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    knolleary/PubSubClient
    bblanchon/ArduinoJson@^6
    madhephaestus/ESP32Servo
    chris--a/Keypad
    miguelbalboa/MFRC522
